# app/agent/grounding.py — the last, structural line of defense for rule #2
# ("grounded output only — every claim cites a source chunk").
#
# WHY THIS EXISTS: the report's source_urls are GENERATED by the synthesis LLM
# (Gemini) from a flattened exploration log — nothing about that step guarantees
# the url it wrote is a page we actually ingested. A confident, well-formatted,
# WRONG citation is the worst possible output for a system whose whole promise
# is "you can check every claim against the source." The schema REQUIRES a
# source_url; it does not verify the url is real. This module does.
#
# WHAT IT DOES: after synthesis, drop any Observation whose source_url is not a
# page in the store. Dropping (not flagging) is the principled choice — an
# unverifiable citation must never reach a founder. unanswered_questions are
# plain strings with no source, so they pass through untouched.
#
# CALL FLOW:
#   report.py generate_report() → enforce_citations(report, store urls)
#       (runs for BOTH drivers, so Gemini and Groq get the identical guarantee)

import logging
from urllib.parse import urlparse

from app.schemas import FirstImpressionReport

logger = logging.getLogger("first_impression")

# The report fields that hold cited Observations (unanswered_questions and
# scope_note carry no source_url, so they are not validated here).
_OBSERVATION_FIELDS = (
    "what_the_product_is",
    "likely_new_user_journey",
    "friction_points",
    "standout_strengths",
)


def _normalize(url: str) -> str:
    """Canonical form for comparison: lowercased scheme+host+path, no trailing
    slash. So 'https://Site.com/Docs/' and 'https://site.com/docs' match, but a
    hallucinated 'https://site.com/blog' still won't match a real '/docs'.
    A bare string with no scheme (not a real url) normalizes to itself so it
    can never accidentally match a stored url."""
    parsed = urlparse(url.strip())
    if not parsed.scheme or not parsed.netloc:
        return url.strip().rstrip("/").lower()
    return f"{parsed.scheme}://{parsed.netloc}{parsed.path.rstrip('/')}".lower()


def enforce_citations(
    report: FirstImpressionReport, valid_urls: list[str]
) -> tuple[FirstImpressionReport, list[dict]]:
    """Remove observations whose source_url is not a real ingested page.

    Called by: report.py generate_report(), after the synthesis call.
    Returns (report, dropped) where `dropped` lists every removed observation
    (field + claim + the bogus url) so the caller can log what was discarded —
    a silent drop would hide a synthesis quality problem.
    """
    valid = {_normalize(u) for u in valid_urls}
    dropped: list[dict] = []

    for field in _OBSERVATION_FIELDS:
        kept = []
        for obs in getattr(report, field):
            if _normalize(obs.source_url) in valid:
                kept.append(obs)
            else:
                dropped.append(
                    {"field": field, "claim": obs.claim, "source_url": obs.source_url}
                )
        setattr(report, field, kept)

    if dropped:
        logger.warning(
            "grounding: dropped %d observation(s) citing non-ingested URLs: %s",
            len(dropped),
            [d["source_url"] for d in dropped],
        )
    return report, dropped
