# app/schemas.py — Pydantic models defining the API's request/response shapes.
#
# WHERE THESE ARE USED:
#   IngestRequest / IngestResponse → main.py ingest()  (POST /ingest)
#   AskRequest / AskResponse       → main.py ask()     (POST /ask)
#   Source                         → nested inside AskResponse
#   Observation / FirstImpressionReport / ReportResponse
#                                  → main.py report()  (POST /report, Phase 3)
#                                    AND agent/report.py as the Gemini
#                                    response_schema (structured output).
#
# FastAPI uses these to (a) reject malformed requests with a 422 before our
# code runs, (b) guarantee responses match the declared shape, and (c) render
# the /docs page. Field(...) constraints are validation RULES, not comments —
# max_pages=999 is rejected by the framework; our code never sees it.

from pydantic import BaseModel, Field, HttpUrl


class IngestRequest(BaseModel):
    """Body of POST /ingest — what site to crawl and how far.

    Validated by FastAPI before main.ingest() runs.
    """

    url: HttpUrl  # HttpUrl (not str) = must parse as a valid http(s) URL
    max_pages: int = Field(default=15, ge=1, le=50)  # ge/le = min/max allowed


class IngestResponse(BaseModel):
    """What POST /ingest returns — a summary of what was crawled and stored.

    Built at the end of main.ingest(); skipped_by_robots comes from
    fetcher.CrawlResult so rule-#1 enforcement is visible to the caller.
    """

    pages_fetched: int
    chunks_stored: int
    skipped_by_robots: int


class AskRequest(BaseModel):
    """Body of POST /ask — the question, and how many chunks to retrieve.

    Validated by FastAPI before main.ask() runs.
    """

    question: str = Field(min_length=3)
    top_k: int = Field(default=5, ge=1, le=10)  # how many chunks to retrieve


class Source(BaseModel):
    """One retrieved chunk shown to the caller as a citation.

    Nested inside AskResponse. `index` matches the [n] markers Claude
    writes in the answer text (numbering assigned in qa.answer()).
    """

    index: int
    url: str
    snippet: str


class AskResponse(BaseModel):
    """What POST /ask returns — the grounded answer plus its citations.

    Built at the end of main.ask(): `answer` from qa.answer(),
    `sources` from the same hits that were given to Claude.
    """

    answer: str
    sources: list[Source]


# ---------------------------------------------------------------------------
# Phase 3: the structured First Impression report.
#
# This schema is doing TWO jobs at once:
#   1. It is the Gemini `response_schema` — the model must generate JSON that
#      fits it, so an Observation without a source_url is literally impossible
#      to produce. That is hard rule #2 (grounded output only) made STRUCTURAL,
#      not just requested in a prompt.
#   2. It is the FastAPI response_model for POST /report — so the /docs page
#      documents the exact report shape and the response is validated on the
#      way out.
# ---------------------------------------------------------------------------


class Observation(BaseModel):
    """One grounded finding. Every field is required — an observation cannot
    exist without the evidence and the page a founder can check it against."""

    claim: str  # e.g. "A prospective user cannot find pricing from the docs"
    evidence: str  # short quote/paraphrase from the site that supports the claim
    source_url: str  # where on the public site this was observed


class ImprovementOpportunity(BaseModel):
    """A friendly, OPTIONAL suggestion — explicitly our inference, NOT a grounded
    observation. Kept in its own type (and its own report field) so advice can
    never be mistaken for a cited fact: the wall between "what a visitor
    experiences" (Observation, defensible) and "what we'd gently suggest"
    (opinion) is what keeps the report both useful and trustworthy.

    Still grounded, though: `observed` names the real first-impression experience
    the suggestion responds to, and `source_url` is the page it came from — so a
    founder can trace the WHY even though the WHAT-TO-DO is our opinion. The
    source_url is citation-verified exactly like an Observation's."""

    observed: str  # the real first-impression experience this responds to
    suggestion: str  # the gentle, constructive idea — an invitation, not a verdict
    source_url: str  # the page the observation came from (verified against the store)


class FirstImpressionReport(BaseModel):
    """The deliverable: a structured, observational read of a company's public
    product surface as experienced by a prospective new user. Generated by the
    agent in agent/report.py; every list holds cited Observations."""

    company: str
    what_the_product_is: list[Observation]
    likely_new_user_journey: list[Observation]  # what the public surface teaches, in order
    friction_points: list[Observation]  # unclear / missing / hard-to-find — described, not graded
    standout_strengths: list[Observation]  # what genuinely works well
    unanswered_questions: list[str]  # what a prospect CANNOT learn before signing up
    # Friendly, constructive suggestions — separate from the cited Observations
    # above so opinion never contaminates fact. Defaults to [] so the model may
    # honestly return none rather than invent filler.
    improvement_opportunities: list[ImprovementOpportunity] = Field(default_factory=list)
    scope_note: str  # honest "public surface only, no login" disclaimer


class ReportResponse(BaseModel):
    """What POST /report returns — the report plus a little transparency about
    HOW the agent produced it (which pages it read, how many tool calls)."""

    report: FirstImpressionReport
    steps_taken: int
    pages_examined: list[str]
    tool_calls: list[str]  # human-readable trace of the agent's actions
